### ISSUE TITLE
 App Keys non-responsive after screen lock. Another Dash to Dock conflict? 

### ISSUE THREAD

**Issue by cswartzvi** [franziskuskiefer/app-keys-gnome-shell-extension#20] opened 2015-10-27 01:49 UTC
I am having a peculiar issue when both *App Keys* and *Dash to Dock* are enabled. It is similar to #17 and micheleg/dash-to-dock#198, however in this case *App Keys* works as expected until the screen is locked, and then subsequently unlocked, where it becomes non-responsive (no noticeable effect to *Dash To Dock*). The issue does not appear when *Dash to Dock* is disabled.  Executing *Alt+F2 r* fixes the issue, but where's the fun in that :-) 

All other extensions are disabled, and looking glass shows no errors for either *App Keys* or *Dash to Dock*.

OS: Fedora 22 (gnome 3.16.4)
*App Key* version: 17
*Dash to Dock* version: 47

Oddly enough, I have the exact same OS and extensions on both my laptop and desktop. Only the desktop has ever produced the above behavior (desktop has dual monitors and a different GPU, if that matters).

Any help or workaround would be greatly appreciated.

**Comment by franziskuskiefer** [comment] 2015-10-27 07:23
hm... interesting. I'll try looking into it but can't reproduce it yet. So let me know if you have any additional information that could help.

**Comment by cswartzvi** [comment] 2015-10-28 02:43
Maybe I'm reaching here, but I looked at `journalctl /usr/bin/gnome-session -f` and this is what is produced during the unlocking and shell reset.  Doesn't look particularly useful (to me) and doesn't call out *App Keys* or *Dash to Dock* directly.

```
gnome-session[2132]: self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
gnome-session[2132]: (gnome-shell:2280): mutter-WARNING **: STACK_OP_ADD: window 0x1c00001 already in stack
gnome-session[2132]: (gnome-shell:2280): mutter-WARNING **: STACK_OP_ADD: window 0x1c00001 already in stack
gnome-session[2132]: (gnome-settings-daemon:2235): color-plugin-WARNING **: could not find device: property match 'XRANDR_name'='HDMI-0' does not exist
gnome-session[2132]: (gnome-settings-daemon:2235): color-plugin-WARNING **: could not find device: property match 'XRANDR_name'='VGA-0' does not exist

```

I will keep looking. Any suggestions on additional tests?

**Comment by franglais125** [comment] 2016-05-12 04:33
Hi,

I'm having this exact problem on gnome-shell 3.18 and 3.20. Can't use the extension after locking the screen, a shell restart fixes it.

Further information: /var/log/user.log shows:
`(gnome-shell:1458): Gjs-WARNING **: JS ERROR: TypeError: apps[id] is undefined
AppKeys.prototype.clickClosure/<@/home/franglais125/.local/share/gnome-shell/extensions/unitylike-hotkey@webgyerek.net/extension.js:54`
every time I try to use <Super>+Num.

Debian Testing and Sid.

**Comment by franglais125** [comment] 2016-05-12 21:32
@cswartzvi I committed a fix for this. Would you mind trying it to see if it works for you too?

This is the pull:
https://github.com/franziskuskiefer/app-keys-gnome-shell-extension/pull/30

This is a fork with the fix included:
https://github.com/franglais125/app-keys-gnome-shell-extension

**Closed** 2016-05-22 17:15 UTC
Labels: bug
